
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT HASH LPAREN RPAREN VARexpr : VARexpr : func argexpr : HASH VAR DOT exprfunc : VARfunc : LPAREN HASH VAR DOT expr RPARENfunc : func argarg : VARarg : LPAREN HASH VAR DOT expr RPARENarg : LPAREN func arg RPAREN'
    
_lr_action_items = {'VAR':([0,2,3,4,6,7,8,10,11,12,13,14,17,19,20,21,24,25,],[2,-4,7,9,-6,-7,12,15,16,-4,7,2,-6,2,2,-9,-5,-8,]),'HASH':([0,5,8,14,19,20,],[4,10,11,4,4,4,]),'LPAREN':([0,2,3,6,7,8,12,13,14,17,19,20,21,24,25,],[5,-4,8,-6,-7,5,-4,8,5,-6,5,5,-9,-5,-8,]),'$end':([1,2,6,7,18,21,25,],[0,-1,-2,-7,-3,-9,-8,]),'RPAREN':([2,6,7,17,18,21,22,23,25,],[-1,-2,-7,21,-3,-9,24,25,-8,]),'DOT':([9,15,16,],[14,19,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,14,19,20,],[1,18,22,23,]),'func':([0,8,14,19,20,],[3,13,3,3,3,]),'arg':([3,13,],[6,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> VAR','expr',1,'p_expr_var','parser_1.py',31),
  ('expr -> func arg','expr',2,'p_expr_func_arg','parser_1.py',35),
  ('expr -> HASH VAR DOT expr','expr',4,'p_expr_lambda','parser_1.py',39),
  ('func -> VAR','func',1,'p_func_var','parser_1.py',43),
  ('func -> LPAREN HASH VAR DOT expr RPAREN','func',6,'p_func_lambda','parser_1.py',47),
  ('func -> func arg','func',2,'p_func_application','parser_1.py',51),
  ('arg -> VAR','arg',1,'p_arg_var','parser_1.py',55),
  ('arg -> LPAREN HASH VAR DOT expr RPAREN','arg',6,'p_arg_lambda','parser_1.py',59),
  ('arg -> LPAREN func arg RPAREN','arg',4,'p_arg_application','parser_1.py',63),
]
